# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu_1 = QtWidgets.QMenu(parent=self.menubar)
        self.menu_1.setObjectName("menu_1")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(parent=self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(parent=self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_show_VUZ = QtGui.QAction(parent=MainWindow)
        self.action_show_VUZ.setObjectName("action_show_VUZ")
        self.action_show_Tp_nir = QtGui.QAction(parent=MainWindow)
        self.action_show_Tp_nir.setObjectName("action_show_Tp_nir")
        self.action_show_grntirub = QtGui.QAction(parent=MainWindow)
        self.action_show_grntirub.setObjectName("action_show_grntirub")
        self.action = QtGui.QAction(parent=MainWindow)
        self.action.setObjectName("action")
        self.action_5 = QtGui.QAction(parent=MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtGui.QAction(parent=MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtGui.QAction(parent=MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_show_Tp_fv = QtGui.QAction(parent=MainWindow)
        self.action_show_Tp_fv.setObjectName("action_show_Tp_fv")
        self.action_9 = QtGui.QAction(parent=MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_10 = QtGui.QAction(parent=MainWindow)
        self.action_10.setObjectName("action_10")
        self.action_11 = QtGui.QAction(parent=MainWindow)
        self.action_11.setObjectName("action_11")

        self.menu.addAction(self.action_7)
        form.action_input_cod_grnti = QtGui.QAction(parent=MainWindow)
        form.action_input_cod_grnti.setText("Добавление кода ГРНТИ")
        form.action_input_cod_grnti.triggered.connect(input_cod_grnti)
        form.menu.addAction(form.action_input_cod_grnti)

        form.action_filter_by_cod_grnti = QtGui.QAction(parent=MainWindow)
        form.action_filter_by_cod_grnti.setText("Фильтрация по коду ГРНТИ")
        form.action_filter_by_cod_grnti.triggered.connect(filter_by_cod_grnti)
        form.menu.addAction(form.action_filter_by_cod_grnti)
        self.menu_1.addAction(self.action_show_VUZ)
        self.menu_1.addSeparator()
        self.menu_1.addAction(self.action_show_Tp_nir)
        self.menu_1.addSeparator()
        self.menu_1.addAction(self.action_show_grntirub)
        self.menu_1.addSeparator()
        self.menu_1.addAction(self.action_show_Tp_fv)
        self.menu.addAction(self.action)
        self.menu.addSeparator()
        self.menu.addAction(self.action_5)
        self.menu.addAction(self.action_6)
        self.menu.addAction(self.action_7)
        self.menu_2.addAction(self.action_9)
        self.menu_2.addAction(self.action_10)
        self.menu_3.addAction(self.action_11)
        self.menubar.addAction(self.menu_1.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_1.setTitle(_translate("MainWindow", "Отображение таблиц"))
        self.menu.setTitle(_translate("MainWindow", "Работа с бд"))
        self.menu_2.setTitle(_translate("MainWindow", "Формирование отчетности"))
        self.menu_3.setTitle(_translate("MainWindow", "Выпуск распоряжения"))
        self.action_show_VUZ.setText(_translate("MainWindow", "VUZ"))
        self.action_show_Tp_nir.setText(_translate("MainWindow", "Tp_nir"))
        self.action_show_grntirub.setText(_translate("MainWindow", "grntirub"))
        self.action.setText(_translate("MainWindow", "Проверка целостности"))
        self.action_5.setText(_translate("MainWindow", "Добавление записи"))
        self.action_6.setText(_translate("MainWindow", "Редактирование"))
        self.action_7.setText(_translate("MainWindow", "Удаление запси"))
        self.action_show_Tp_fv.setText(_translate("MainWindow", "Tp_fv"))
        self.action_9.setText(_translate("MainWindow", "Формирование документов"))
        self.action_10.setText(_translate("MainWindow", "Сохранение условий фильтрации"))
        self.action_11.setText(_translate("MainWindow", "Сформировать распоряжение"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(160, 180, 311, 271))
        self.tableView.setObjectName("tableView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menudsdd = QtWidgets.QMenu(parent=self.menubar)
        self.menudsdd.setObjectName("menudsdd")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_try = QtGui.QAction(parent=MainWindow)
        self.action_try.setObjectName("action_try")
        self.menudsdd.addAction(self.action_try)
        self.menubar.addAction(self.menudsdd.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menudsdd.setTitle(_translate("MainWindow", "dsdd"))
        self.action_try.setText(_translate("MainWindow", "try"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
